application: proyectoequipouno
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
 
- url: /public/img
  static_dir: public/img

- url: /static/bootstrap/js
  static_dir: static/bootstrap/js
  
- url: /.*
  script: app.app

# - url: /_ah/mail/.+
#   script: handle_incoming_email.app

libraries:
- name: jinja2
  version: latest

